FROM registry.redhat.io/ubi8:latest
RUN mkdir /home/cybersec
WORKDIR /home/cybersec
COPY ./serversec.py /home/cybersec
RUN yum install -y python38
RUN python3.8 -m pip install flask
RUN python3.8 -m pip install Flask-RESTful
RUN python3.8 -m pip install -U flask-cors
RUN python3.8 -m pip install pyotp
ENTRYPOINT python3.8 ./serversec.py
EXPOSE 5000 
